# site settings
title: Curtis Getz - Android Developer
subtitle: 
email: CurtisGetz@gmail.com
description: A dedicated Android developer with a passion for building functional Android applications. A recipient of Grow with Google Scholarship and a graduate of Udacity’s Android Developer Nanodegree program. Many years of experience in tech support.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Croydon
state: PA
zip_code: 19021
country: United States of America
phone: (267) 540-3420

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/curtisgetz
gitlab_url:
googleplus_url: 
instagram_url:  
linkedin_url: https://www.linkedin.com/in/curtis-getz/
pinterest_url:
slack_url:
twitter_url:  

# build settings
markdown: kramdown

sass:
  style: compressed
